### ISSUE TITLE
Fatal error when downloading

### ISSUE THREAD

**Issue by tmkklivecom** [Piwigo/Piwigo-BatchDownloader#30]
Fatal error: Uncaught ArgumentCountError: Too few arguments to function get_extended_desc_cliext(), 1 passed in /volume1/web/piwigo_test/include/functions_plugins.inc.php on line 214 and exactly 2 expected in /volume1/web/piwigo_test/plugins/PiwigoClientWsExts/include/pwg.extended_description.php:25 Stack trace: #0 /volume1/web/piwigo_test/include/functions_plugins.inc.php(214): get_extended_desc_cliext('') #1 /volume1/web/piwigo_test/plugins/BatchDownloader/include/BatchDownloader.class.php(786): trigger_change('render_category...', '') #2 /volume1/web/piwigo_test/plugins/BatchDownloader/include/BatchDownloader.class.php(937): BatchDownloader->getNames() #3 /volume1/web/piwigo_test/plugins/BatchDownloader/include/events.inc.php(230): BatchDownloader->getSetInfo() #4 /volume1/web/piwigo_test/include/functions_plugins.inc.php(264): batch_download_applymenu(Array) #5 /volume1/web/piwigo_test/include/block.class.php(181): trigger_notify('blockmanager_ap...', Array) #6 /volume1/web/piwigo_test/include/menubar.inc.php(342): Bl in /volume1/web/piwigo_test/plugins/PiwigoClientWsExts/include/pwg.extended_description.php on line 25

**Comment by tmkklivecom** [comment]
The problem is in PiwigoClientWsExts
