### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by nilsthoma** [Piwigo/Piwigo-BatchDownloader#57]
Hi,
latest BDL version on Piwigo 14 shows the following error when ticking the settings button – anything I can do?:

Warning: Undefined array key "request_permission" in /home/www/jazz-club-trier.info/pwg/plugins/BatchDownloader/admin.php on line 13

Fatal error: Uncaught mysqli_sql_exception: Table 'web98_db1.piwigo_download_requests' doesn't exist in /home/www/jazz-club-trier.info/pwg/include/dblayer/functions_mysqli.inc.php:132 Stack trace: #0 /home/www/jazz-club-trier.info/pwg/include/dblayer/functions_mysqli.inc.php(132): mysqli->query('\nSELECT\n\t s.id ...') #1 /home/www/jazz-club-trier.info/pwg/include/dblayer/functions_mysqli.inc.php(888): pwg_query('\nSELECT\n\t s.id ...') #2 /home/www/jazz-club-trier.info/pwg/plugins/BatchDownloader/admin/sets.php(112): query2array('\nSELECT\n\t s.id ...', 'set_id', 'request_id') #3 /home/www/jazz-club-trier.info/pwg/plugins/BatchDownloader/admin.php(37): include('/home/www/jazz-...') #4 /home/www/jazz-club-trier.info/pwg/admin/plugin.php(53): include_once('/home/www/jazz-...') #5 /home/www/jazz-club-trier.info/pwg/admin.php(346): include('/home/www/jazz-...') #6 {main} thrown in /home/www/jazz-club-trier.info/pwg/include/dblayer/functions_mysqli.inc.php on line 132

**Comment by willemb2** [comment]
While the BDL was still working on the front-end, we got the same error when I went to the plugin settings. I managed to fix it by clicking the 3 dots and clicking 'Restore'. According to the description, this resets BDL to its original parameters.


-     Piwigo 14.5.0
-     Installed on 2 March 2023, 1 year 4 months 2 weeks 4 days ago
-     Operating system: Linux
-     PHP: 8.1.29 (Show info) [2024-07-21 12:56:49]
-     MySQL: 10.11.7-MariaDB-cll-lve [2024-07-21 12:56:49]
-     Graphics Library: ImageMagick 6.9.13-10
-     Cache size 1602.45 Mo   

Activated plugin list 8

-     Batch Downloader
-     Check Uploads
-     Force HTTPS
-     LocalFiles Editor
-     Manage Properties Photos
-     Personal Plugin
-     Read Metadata
-     Write Metadata
